/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CountryAttributes model module.
 * @module model/CountryAttributes
 * @version 0.1.0
 */
export class CountryAttributes {
  /**
   * Constructs a new <code>CountryAttributes</code>.
   * @alias module:model/CountryAttributes
   * @class
   * @param code {String} 
   */
  constructor(code) {
    this.code = code;
  }

  /**
   * Constructs a <code>CountryAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CountryAttributes} obj Optional instance to populate.
   * @return {module:model/CountryAttributes} The populated <code>CountryAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CountryAttributes();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
CountryAttributes.prototype.code = undefined;

