/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Filter model module.
 * @module model/Filter
 * @version 0.1.0
 */
export class Filter {
  /**
   * Constructs a new <code>Filter</code>.
   * @alias module:model/Filter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Filter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Filter} obj Optional instance to populate.
   * @return {module:model/Filter} The populated <code>Filter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Filter();
      if (data.hasOwnProperty('min_pages'))
        obj.minPages = ApiClient.convertToType(data['min_pages'], 'Number');
      if (data.hasOwnProperty('max_pages'))
        obj.maxPages = ApiClient.convertToType(data['max_pages'], 'Number');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('min_year'))
        obj.minYear = ApiClient.convertToType(data['min_year'], 'Number');
      if (data.hasOwnProperty('max_year'))
        obj.maxYear = ApiClient.convertToType(data['max_year'], 'Number');
      if (data.hasOwnProperty('institution'))
        obj.institution = ApiClient.convertToType(data['institution'], Object);
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], Object);
      if (data.hasOwnProperty('publisher'))
        obj.publisher = ApiClient.convertToType(data['publisher'], 'String');
      if (data.hasOwnProperty('dblp_type'))
        obj.dblpType = ApiClient.convertToType(data['dblp_type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} minPages
 */
Filter.prototype.minPages = undefined;

/**
 * @member {Number} maxPages
 */
Filter.prototype.maxPages = undefined;

/**
 * @member {Number} year
 */
Filter.prototype.year = undefined;

/**
 * @member {Number} minYear
 */
Filter.prototype.minYear = undefined;

/**
 * @member {Number} maxYear
 */
Filter.prototype.maxYear = undefined;

/**
 * @member {Object} institution
 */
Filter.prototype.institution = undefined;

/**
 * @member {Object} source
 */
Filter.prototype.source = undefined;

/**
 * @member {String} publisher
 */
Filter.prototype.publisher = undefined;

/**
 * @member {String} dblpType
 */
Filter.prototype.dblpType = undefined;

