/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OneOfid5 model module.
 * @module model/OneOfid5
 * @version 0.1.0
 */
export class OneOfid5 {
  /**
   * Constructs a new <code>OneOfid5</code>.
   * @alias module:model/OneOfid5
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfid5</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfid5} obj Optional instance to populate.
   * @return {module:model/OneOfid5} The populated <code>OneOfid5</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfid5();
    }
    return obj;
  }
}
