/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PersonAttributes model module.
 * @module model/PersonAttributes
 * @version 0.1.0
 */
export class PersonAttributes {
  /**
   * Constructs a new <code>PersonAttributes</code>.
   * @alias module:model/PersonAttributes
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PersonAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersonAttributes} obj Optional instance to populate.
   * @return {module:model/PersonAttributes} The populated <code>PersonAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PersonAttributes();
      if (data.hasOwnProperty('affiliation'))
        obj.affiliation = ApiClient.convertToType(data['affiliation'], 'String');
      if (data.hasOwnProperty('homepage'))
        obj.homepage = ApiClient.convertToType(data['homepage'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} affiliation
 */
PersonAttributes.prototype.affiliation = undefined;

/**
 * @member {String} homepage
 */
PersonAttributes.prototype.homepage = undefined;

/**
 * @member {String} notes
 */
PersonAttributes.prototype.notes = undefined;

