/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PublicationAttributes model module.
 * @module model/PublicationAttributes
 * @version 0.1.0
 */
export class PublicationAttributes {
  /**
   * Constructs a new <code>PublicationAttributes</code>.
   * @alias module:model/PublicationAttributes
   * @class
   * @param dBLPType {String} 
   * @param electronicEdition {String} 
   * @param year {Number} 
   */
  constructor(dBLPType, electronicEdition, year) {
    this.dBLPType = dBLPType;
    this.electronicEdition = electronicEdition;
    this.year = year;
  }

  /**
   * Constructs a <code>PublicationAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PublicationAttributes} obj Optional instance to populate.
   * @return {module:model/PublicationAttributes} The populated <code>PublicationAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PublicationAttributes();
      if (data.hasOwnProperty('DBLP_type'))
        obj.dBLPType = ApiClient.convertToType(data['DBLP_type'], 'String');
      if (data.hasOwnProperty('electronic_edition'))
        obj.electronicEdition = ApiClient.convertToType(data['electronic_edition'], 'String');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('cross_ref'))
        obj.crossRef = ApiClient.convertToType(data['cross_ref'], 'String');
      if (data.hasOwnProperty('number_of_pages'))
        obj.numberOfPages = ApiClient.convertToType(data['number_of_pages'], 'Number');
      if (data.hasOwnProperty('pages'))
        obj.pages = ApiClient.convertToType(data['pages'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('school'))
        obj.school = ApiClient.convertToType(data['school'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('notes'))
        obj.notes = ApiClient.convertToType(data['notes'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} dBLPType
 */
PublicationAttributes.prototype.dBLPType = undefined;

/**
 * @member {String} electronicEdition
 */
PublicationAttributes.prototype.electronicEdition = undefined;

/**
 * @member {Number} year
 */
PublicationAttributes.prototype.year = undefined;

/**
 * @member {String} crossRef
 */
PublicationAttributes.prototype.crossRef = undefined;

/**
 * @member {Number} numberOfPages
 */
PublicationAttributes.prototype.numberOfPages = undefined;

/**
 * @member {String} pages
 */
PublicationAttributes.prototype.pages = undefined;

/**
 * @member {String} source
 */
PublicationAttributes.prototype.source = undefined;

/**
 * @member {String} school
 */
PublicationAttributes.prototype.school = undefined;

/**
 * @member {String} url
 */
PublicationAttributes.prototype.url = undefined;

/**
 * @member {String} notes
 */
PublicationAttributes.prototype.notes = undefined;

