/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SourceAttributes model module.
 * @module model/SourceAttributes
 * @version 0.1.0
 */
export class SourceAttributes {
  /**
   * Constructs a new <code>SourceAttributes</code>.
   * @alias module:model/SourceAttributes
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SourceAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SourceAttributes} obj Optional instance to populate.
   * @return {module:model/SourceAttributes} The populated <code>SourceAttributes</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SourceAttributes();
      if (data.hasOwnProperty('DBLP_type'))
        obj.dBLPType = ApiClient.convertToType(data['DBLP_type'], 'String');
      if (data.hasOwnProperty('electronic_edition'))
        obj.electronicEdition = ApiClient.convertToType(data['electronic_edition'], 'String');
      if (data.hasOwnProperty('isbn'))
        obj.isbn = ApiClient.convertToType(data['isbn'], 'String');
      if (data.hasOwnProperty('publisher'))
        obj.publisher = ApiClient.convertToType(data['publisher'], 'String');
      if (data.hasOwnProperty('series'))
        obj.series = ApiClient.convertToType(data['series'], 'String');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} dBLPType
 */
SourceAttributes.prototype.dBLPType = undefined;

/**
 * @member {String} electronicEdition
 */
SourceAttributes.prototype.electronicEdition = undefined;

/**
 * @member {String} isbn
 */
SourceAttributes.prototype.isbn = undefined;

/**
 * @member {String} publisher
 */
SourceAttributes.prototype.publisher = undefined;

/**
 * @member {String} series
 */
SourceAttributes.prototype.series = undefined;

/**
 * @member {Number} year
 */
SourceAttributes.prototype.year = undefined;

