/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BaseCaSeApiDraft);
  }
}(this, function(expect, BaseCaSeApiDraft) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BaseCaSeApiDraft.CountriesAndContinentsApi();
  });

  describe('(package)', function() {
    describe('CountriesAndContinentsApi', function() {
      describe('continentsGet', function() {
        it('should call continentsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for continentsGet call and complete the assertions
          /*
          var opts = {};

          instance.continentsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse20016);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('continentsIdCountriesGet', function() {
        it('should call continentsIdCountriesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for continentsIdCountriesGet call and complete the assertions
          /*

          instance.continentsIdCountriesGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse20018);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('continentsIdGet', function() {
        it('should call continentsIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for continentsIdGet call and complete the assertions
          /*

          instance.continentsIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse20017);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('continentsIdInstitutionsGet', function() {
        it('should call continentsIdInstitutionsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for continentsIdInstitutionsGet call and complete the assertions
          /*

          instance.continentsIdInstitutionsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countriesGet', function() {
        it('should call countriesGet successfully', function(done) {
          // TODO: uncomment, update parameter values for countriesGet call and complete the assertions
          /*
          var opts = {};

          instance.countriesGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse20014);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countriesIdGet', function() {
        it('should call countriesIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for countriesIdGet call and complete the assertions
          /*

          instance.countriesIdGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse20015);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('countriesIdInstitutionsGet', function() {
        it('should call countriesIdInstitutionsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for countriesIdInstitutionsGet call and complete the assertions
          /*

          instance.countriesIdInstitutionsGet(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(BaseCaSeApiDraft.InlineResponse2009);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
