/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Continent} from './model/Continent';
import {Country} from './model/Country';
import {CountryAttributes} from './model/CountryAttributes';
import {Error} from './model/Error';
import {Filter} from './model/Filter';
import {Id} from './model/Id';
import {Id1} from './model/Id1';
import {Id2} from './model/Id2';
import {Id3} from './model/Id3';
import {Id4} from './model/Id4';
import {Id5} from './model/Id5';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse20010} from './model/InlineResponse20010';
import {InlineResponse20011} from './model/InlineResponse20011';
import {InlineResponse20012} from './model/InlineResponse20012';
import {InlineResponse20013} from './model/InlineResponse20013';
import {InlineResponse20014} from './model/InlineResponse20014';
import {InlineResponse20015} from './model/InlineResponse20015';
import {InlineResponse20016} from './model/InlineResponse20016';
import {InlineResponse20017} from './model/InlineResponse20017';
import {InlineResponse20018} from './model/InlineResponse20018';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse2004} from './model/InlineResponse2004';
import {InlineResponse2005} from './model/InlineResponse2005';
import {InlineResponse2006} from './model/InlineResponse2006';
import {InlineResponse2007} from './model/InlineResponse2007';
import {InlineResponse2008} from './model/InlineResponse2008';
import {InlineResponse2009} from './model/InlineResponse2009';
import {Institution} from './model/Institution';
import {InstitutionAttributes} from './model/InstitutionAttributes';
import {OneOffilterInstitution} from './model/OneOffilterInstitution';
import {OneOffilterSource} from './model/OneOffilterSource';
import {OneOfid} from './model/OneOfid';
import {OneOfid1} from './model/OneOfid1';
import {OneOfid2} from './model/OneOfid2';
import {OneOfid3} from './model/OneOfid3';
import {OneOfid4} from './model/OneOfid4';
import {OneOfid5} from './model/OneOfid5';
import {Person} from './model/Person';
import {PersonAttributes} from './model/PersonAttributes';
import {Publication} from './model/Publication';
import {PublicationAttributes} from './model/PublicationAttributes';
import {Source} from './model/Source';
import {SourceAttributes} from './model/SourceAttributes';
import {CountriesAndContinentsApi} from './api/CountriesAndContinentsApi';
import {InstitutionsApi} from './api/InstitutionsApi';
import {PeopleApi} from './api/PeopleApi';
import {PublicationSourcesAndCollectionsApi} from './api/PublicationSourcesAndCollectionsApi';
import {PublicationsApi} from './api/PublicationsApi';
import {UserAccountsApi} from './api/UserAccountsApi';

/**
* Preliminary_OpenAPI_documentation__Subject_to_change_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var BaseCaSeApiDraft = require('index'); // See note below*.
* var xxxSvc = new BaseCaSeApiDraft.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new BaseCaSeApiDraft.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new BaseCaSeApiDraft.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new BaseCaSeApiDraft.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Continent model constructor.
     * @property {module:model/Continent}
     */
    Continent,

    /**
     * The Country model constructor.
     * @property {module:model/Country}
     */
    Country,

    /**
     * The CountryAttributes model constructor.
     * @property {module:model/CountryAttributes}
     */
    CountryAttributes,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter,

    /**
     * The Id model constructor.
     * @property {module:model/Id}
     */
    Id,

    /**
     * The Id1 model constructor.
     * @property {module:model/Id1}
     */
    Id1,

    /**
     * The Id2 model constructor.
     * @property {module:model/Id2}
     */
    Id2,

    /**
     * The Id3 model constructor.
     * @property {module:model/Id3}
     */
    Id3,

    /**
     * The Id4 model constructor.
     * @property {module:model/Id4}
     */
    Id4,

    /**
     * The Id5 model constructor.
     * @property {module:model/Id5}
     */
    Id5,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse20014 model constructor.
     * @property {module:model/InlineResponse20014}
     */
    InlineResponse20014,

    /**
     * The InlineResponse20015 model constructor.
     * @property {module:model/InlineResponse20015}
     */
    InlineResponse20015,

    /**
     * The InlineResponse20016 model constructor.
     * @property {module:model/InlineResponse20016}
     */
    InlineResponse20016,

    /**
     * The InlineResponse20017 model constructor.
     * @property {module:model/InlineResponse20017}
     */
    InlineResponse20017,

    /**
     * The InlineResponse20018 model constructor.
     * @property {module:model/InlineResponse20018}
     */
    InlineResponse20018,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The Institution model constructor.
     * @property {module:model/Institution}
     */
    Institution,

    /**
     * The InstitutionAttributes model constructor.
     * @property {module:model/InstitutionAttributes}
     */
    InstitutionAttributes,

    /**
     * The OneOffilterInstitution model constructor.
     * @property {module:model/OneOffilterInstitution}
     */
    OneOffilterInstitution,

    /**
     * The OneOffilterSource model constructor.
     * @property {module:model/OneOffilterSource}
     */
    OneOffilterSource,

    /**
     * The OneOfid model constructor.
     * @property {module:model/OneOfid}
     */
    OneOfid,

    /**
     * The OneOfid1 model constructor.
     * @property {module:model/OneOfid1}
     */
    OneOfid1,

    /**
     * The OneOfid2 model constructor.
     * @property {module:model/OneOfid2}
     */
    OneOfid2,

    /**
     * The OneOfid3 model constructor.
     * @property {module:model/OneOfid3}
     */
    OneOfid3,

    /**
     * The OneOfid4 model constructor.
     * @property {module:model/OneOfid4}
     */
    OneOfid4,

    /**
     * The OneOfid5 model constructor.
     * @property {module:model/OneOfid5}
     */
    OneOfid5,

    /**
     * The Person model constructor.
     * @property {module:model/Person}
     */
    Person,

    /**
     * The PersonAttributes model constructor.
     * @property {module:model/PersonAttributes}
     */
    PersonAttributes,

    /**
     * The Publication model constructor.
     * @property {module:model/Publication}
     */
    Publication,

    /**
     * The PublicationAttributes model constructor.
     * @property {module:model/PublicationAttributes}
     */
    PublicationAttributes,

    /**
     * The Source model constructor.
     * @property {module:model/Source}
     */
    Source,

    /**
     * The SourceAttributes model constructor.
     * @property {module:model/SourceAttributes}
     */
    SourceAttributes,

    /**
    * The CountriesAndContinentsApi service constructor.
    * @property {module:api/CountriesAndContinentsApi}
    */
    CountriesAndContinentsApi,

    /**
    * The InstitutionsApi service constructor.
    * @property {module:api/InstitutionsApi}
    */
    InstitutionsApi,

    /**
    * The PeopleApi service constructor.
    * @property {module:api/PeopleApi}
    */
    PeopleApi,

    /**
    * The PublicationSourcesAndCollectionsApi service constructor.
    * @property {module:api/PublicationSourcesAndCollectionsApi}
    */
    PublicationSourcesAndCollectionsApi,

    /**
    * The PublicationsApi service constructor.
    * @property {module:api/PublicationsApi}
    */
    PublicationsApi,

    /**
    * The UserAccountsApi service constructor.
    * @property {module:api/UserAccountsApi}
    */
    UserAccountsApi
};
