/*
 * BaseCaSE API Draft
 * Preliminary OpenAPI documentation. Subject to change.
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BaseCaSeApiDraft);
  }
}(this, function(expect, BaseCaSeApiDraft) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PersonAttributes', function() {
      beforeEach(function() {
        instance = new BaseCaSeApiDraft.PersonAttributes();
      });

      it('should create an instance of PersonAttributes', function() {
        // TODO: update the code to test PersonAttributes
        expect(instance).to.be.a(BaseCaSeApiDraft.PersonAttributes);
      });

      it('should have the property affiliation (base name: "affiliation")', function() {
        // TODO: update the code to test the property affiliation
        expect(instance).to.have.property('affiliation');
        // expect(instance.affiliation).to.be(expectedValueLiteral);
      });

      it('should have the property homepage (base name: "homepage")', function() {
        // TODO: update the code to test the property homepage
        expect(instance).to.have.property('homepage');
        // expect(instance.homepage).to.be(expectedValueLiteral);
      });

      it('should have the property notes (base name: "notes")', function() {
        // TODO: update the code to test the property notes
        expect(instance).to.have.property('notes');
        // expect(instance.notes).to.be(expectedValueLiteral);
      });

    });
  });

}));
